/******************************************************************************/
/****        Generated by IBExpert 2013.2.15.1 08/03/2022 22:12:32         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES ISO8859_1;

CREATE DATABASE 'LOCALHOST/3052:C:\Teste\BancoTeste.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET ISO8859_1 COLLATION ISO8859_1;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_CLIENTES;
SET GENERATOR GEN_CLIENTES TO 0;

CREATE GENERATOR GEN_TELEFONES;
SET GENERATOR GEN_TELEFONES TO 0;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE CLIENTES (
    ID_CLIENTE     INTEGER NOT NULL,
    NOME           VARCHAR(60) NOT NULL,
    PESSOA_FISICA  SMALLINT NOT NULL,
    CPF_CNPJ       VARCHAR(18) NOT NULL,
    RG_IE          VARCHAR(20),
    DATA_CADASTRO  TIMESTAMP,
    ATIVO          SMALLINT,
    CEP            VARCHAR(8),
    LOGRADOURO     VARCHAR(60),
    NUMERO         VARCHAR(60),
    BAIRRO         VARCHAR(60),
    CIDADE         VARCHAR(60),
    UF             VARCHAR(2),
    PAIS           VARCHAR(60)
);


CREATE TABLE TELEFONES_CLIENTES (
    ID_TELEFONE  INTEGER NOT NULL,
    ID_CLIENTE   INTEGER NOT NULL,
    TELEFONE     VARCHAR(11) NOT NULL,
    RAMAL        VARCHAR(10),
    DESCRICAO    VARCHAR(20)
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE);
ALTER TABLE TELEFONES_CLIENTES ADD CONSTRAINT PK_TELEFONES_CLIENTES PRIMARY KEY (ID_TELEFONE);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE TELEFONES_CLIENTES ADD CONSTRAINT FK_TELEFONES_CLIENTES_1 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);


/******************************************************************************/
/****                               Indices                                ****/
/******************************************************************************/

CREATE INDEX CLIENTES_IDX_ATIVO ON CLIENTES (ATIVO);
CREATE INDEX CLIENTES_IDX_CPF_CNPJ ON CLIENTES (CPF_CNPJ);
CREATE INDEX CLIENTES_IDX_NOME ON CLIENTES (NOME);
CREATE DESCENDING INDEX CLIENTES_IDX_NOME_DESC ON CLIENTES (NOME);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: TELEFONES_CLIENTES_BI5 */
CREATE TRIGGER TELEFONES_CLIENTES_BI5 FOR TELEFONES_CLIENTES
ACTIVE BEFORE INSERT POSITION 5
AS
begin
    if (new.id_telefone = 0) then
        new.id_telefone = gen_id(gen_telefones, 1);
end
^


/* Trigger: TRIG_CLIENTES_BI5 */
CREATE TRIGGER TRIG_CLIENTES_BI5 FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 5
AS
begin
    new.data_cadastro = current_timestamp;
end
^


SET TERM ; ^



/******************************************************************************/
/****                         Fields descriptions                          ****/
/******************************************************************************/

DESCRIBE FIELD PESSOA_FISICA TABLE CLIENTES
'1 SE FISICA; 0 SE JURIDICA';

DESCRIBE FIELD ATIVO TABLE CLIENTES
'1 SE ATIVO; 0 SE INATIVO';

